# Generated by Django 5.2.6 on 2026-04-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_loandetails_loandetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(choices=[('borrowed', 'Đã mượn'), ('returned', 'Đã trả'), ('overdue', 'Quá hạn')], default='borrowed', max_length=20),
        ),
    ]
