# Generated by Django 5.2.11 on 2026-04-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_alter_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Số lượng mượn'),
        ),
    ]
