# Generated by Django 5.2.11 on 2026-06-14 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loandetail_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandetail',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Số lượng đã trả'),
        ),
    ]
