# Generated by Django 5.2.11 on 2026-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Độc Giả'), ('librarian', 'Thủ Thư'), ('manager', 'Quản Lý')], default='reader', max_length=20),
        ),
    ]
